// Mocks generated by Mockito 5.0.7 from annotations
// in events_feed/test/application/map_selector/map_selector_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:events_feed/domain/map_selector_failure.dart' as _i5;
import 'package:events_feed/domain/map_selector_repository.dart' as _i3;
import 'package:events_feed/domain/shared/location.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [MapSelectorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapSelectorRepository extends _i1.Mock
    implements _i3.MapSelectorRepository {
  MockMapSelectorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.MapSelectorFailure, _i6.DomainLocation>>
      getUserLocation() => (super.noSuchMethod(
          Invocation.method(#getUserLocation, []),
          returnValue: Future<
                  _i2.Either<_i5.MapSelectorFailure, _i6.DomainLocation>>.value(
              _FakeEither<_i5.MapSelectorFailure, _i6.DomainLocation>())) as _i4
          .Future<_i2.Either<_i5.MapSelectorFailure, _i6.DomainLocation>>);
}
